### ISSUE TITLE
Cant use browsermob with codeception 

### ISSUE THREAD

**Issue by saiedtrife** [edno/codeception-browsermob#8]
Hi, 

I want to use browsermob to get the HAR file from a website
I am using accepting testing

I tried to install using composer 

When I tried to run the test I am getting erro 

```
  [Codeception\Exception\ModuleException]                                                                       
  Codeception\Extension\BrowserMob: cURL error 7: Failed to connect to localhost port 8080: Connection refused  
```

I am not sure if I installed currently.

Could you please provide information with correct of installiation with codeception with example ?

**Comment by saiedtrife** [comment]
well How I install 

I run :   
1-composer require edno/codeception-browsermob in my codeception folder 
2-it creates new folder under the vendor called 'endo''
3-inside 'endo' there is other composer 
4-I install this composer 
5-it i install all the files shown here in github 
6- I copy the BrowserMob to 
`vendor/codeception/codeception/src/codeception/model` (more convenience) to use it as model

I tired to change the config in my 
`accept.sut.yml` to:

```
class_name: AcceptanceTester
modules:
    enabled:
            - Asserts
            - Mailer
            - EcoProdBot:
                        oauth_token: DQVJ0M1FKVzdIVks1aDZAVVmVrbjZADbWtidTh1RFBPMDdvQ1lyZAjMtM2RoVkdaNTVDcFVZATFVTQVNiSDcyYTMxVlVJdktIdV9kMHpZAYkE2blRoVXkxcUt6ZAUl1NWxyS3lGQmMxU3hETGcwRUh3bFMyNGpqTHJkdE5Nd1ZAyc3JQZADZAqZAElzVkV2N3V4NGx3WS0wcUctUWtGb1NtMHk4WnBsRkRTYjFhNUlKWVV1ZA0t5SVBaeUJpdGRLM3NEbkV1VkxoZAzZAjRmJlekpVaUF6SndOSwZDZD
            - \Helper\Acceptance
            - WebDriver:
                             browser: chrome
                             url: https://creditplus.ru/
                             window_size: 1376x768
                             platform: WINDOW
           - BrowserMob:
                host: 'localhost'
                port: 8080
```
here I stuck I need to know how I can use BrowserMob 
as model 
where I can use getHar with acceptance tester ($I)
to get the HAR file from anywebsite ?
